# Generated by Django 5.0.3 on 2024-04-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('codigo', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=90)),
                ('descripcion', models.CharField(max_length=2000)),
                ('publish', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('imageproj', models.FileField(null=True, upload_to='proyectos/')),
            ],
        ),
    ]
