# Generated by Django 5.0.3 on 2024-04-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle_tips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='imageproj',
            field=models.FileField(null=True, upload_to='tips/'),
        ),
    ]
