# Generated by Django 5.0.3 on 2024-04-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle_tips', '0002_alter_tip_imageproj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
