# Generated by Django 5.0.3 on 2024-05-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora_huella', '0002_pregunta_orden_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcion',
            name='consejo',
            field=models.TextField(blank=True),
        ),
    ]
