# Generated by Django 5.0.3 on 2024-05-05 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora_huella', '0004_intento'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='intento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calculadora_huella.intento'),
        ),
    ]
