# Generated by Django 5.0.3 on 2024-04-29 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
